from mcp.server.fastmcp import FastMCP
from .parser import Parser
from .serializers.code import CodeSerializer
from .serializers.json import JsonSerializer
from .serializers.callers import CallersSerializer

mcp = FastMCP("harpoon")


@mcp.tool()
def trace_code(file_path: str, name: str) -> str:
    """Use this tool whenever you need to understand how a Python function, method, or class works.

    Prefer this over Read when the target may call other functions, use global variables,
    or import from other files — this tool automatically follows all dependencies across
    files and returns a single self-contained code block with everything needed to understand
    the logic. No need to manually open multiple files or chase imports.

    IMPORTANT: the output is a VIRTUAL file — it is generated by assembling code from multiple
    real source files. It does not exist on disk and should not be treated as a real file path.
    Use it for reading and understanding only. If you need to edit code, use the real source
    file paths shown in the `# file:` comments inside the output.

    Use for: explaining logic, debugging, code review, understanding what a function depends on.
    Use dotted notation for methods and nested classes (e.g. MyClass.method, Outer.Inner.method).

    Args:
        file_path: Absolute or relative path to the Python source file containing the target.
        name: Name of the function, method, or class to trace.
    """
    graph = Parser().trace(file_path, name)
    return CodeSerializer().translate(graph)


@mcp.tool()
def trace_graph(file_path: str, name: str) -> str:
    """Use this tool when you need a structural overview of what a Python function, method,
    or class depends on — without reading all the code.

    Returns a JSON graph where each node is a symbol (function, class, or variable) with
    its file path, type, and list of direct dependencies. Useful for understanding the
    dependency structure before diving into code, or for answering questions like
    "what does this function touch?" or "how many layers deep does this go?".

    Use dotted notation for methods and nested classes (e.g. MyClass.method, Outer.Inner.method).

    Args:
        file_path: Absolute or relative path to the Python source file containing the target.
        name: Name of the function, method, or class to trace.
    """
    graph = Parser().trace(file_path, name)
    return JsonSerializer().translate(graph)


@mcp.tool()
def trace_callers(file_path: str, name: str, search_path: str = None) -> str:
    """Use this tool to find all functions and methods that call a specific Python symbol.

    Scans all Python files under search_path (defaults to the directory of file_path) and
    returns a JSON graph of every function that directly or transitively calls the target.
    Edges point from caller to callee, so you can trace the full call chain leading to the target.

    Useful for: understanding the impact of changing a function, finding all entry points that
    reach a specific piece of code, or answering "who calls this?".

    Use dotted notation for methods and nested classes (e.g. MyClass.method, Outer.Inner.method).

    Args:
        file_path: Absolute or relative path to the Python source file containing the target.
        name: Name of the function, method, or class to find callers for.
        search_path: Directory to scan for callers. Defaults to the directory of file_path.
                     Pass a broader path (e.g. the project root) to find callers across the whole codebase.
    """
    graph = Parser().trace_callers(file_path, name, search_path)
    return CallersSerializer().translate(graph)


def main():
    mcp.run()


if __name__ == "__main__":
    main()
